# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target caffe
ADD_LIBRARY(caffe SHARED IMPORTED)

# Create imported target proto
ADD_LIBRARY(proto STATIC IMPORTED)

# Import target "caffe" for configuration "Release"
SET_PROPERTY(TARGET caffe APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(caffe PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "proto;proto;/usr/lib/libboost_system-mt.so;/usr/lib/libboost_thread-mt.so;-lpthread;/usr/local/lib/libglog.so;/usr/lib/x86_64-linux-gnu/libgflags.so;/usr/lib/libprotobuf.so;/usr/lib/libhdf5_hl.so;/usr/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/liblmdb.so;/usr/lib/libleveldb.a;/usr/lib/libsnappy.so;/usr/local/cuda-7.0/lib64/libcudart.so;/usr/local/cuda-7.0/lib64/libcurand.so;/usr/local/cuda-7.0/lib64/libcublas.so;opencv_gpu;opencv_contrib;opencv_legacy;opencv_objdetect;opencv_calib3d;opencv_features2d;opencv_video;opencv_highgui;opencv_ml;opencv_imgproc;opencv_flann;opencv_core;/usr/lib/liblapack_atlas.so;/usr/lib/atlas-base/libptcblas.a;/usr/lib/libatlas.so"
  IMPORTED_LOCATION_RELEASE "/home/sphere/gait_cnn/Caffe/caffe/BLD/lib/libcaffe.so"
  IMPORTED_SONAME_RELEASE "libcaffe.so"
  )

# Import target "proto" for configuration "Release"
SET_PROPERTY(TARGET proto APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(proto PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "/home/sphere/gait_cnn/Caffe/caffe/BLD/lib/libproto.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
